controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_sport:
    resource: '../src/Controller/SportController.php'
    type: annotation
    prefix: '/api/sports'

api_event:
    resource: '../src/Controller/EventController.php'
    type: annotation
    prefix: '/api/events'

api_participant:
    resource: '../src/Controller/ParticipantController.php'
    type: annotation
    prefix: '/api/participants'

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routes.yaml"
    prefix: /api/doc